### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by zhmingzhaung** [NiuTrans/Classical-Modern#13]
无法git clone https://github.com/xiu-ze/Classical-Modern-Corpus.git
打开网址404 not found

**Comment by xiu-ze** [comment]
您好，感谢您的关注，请问您在哪里获得的这个地址？正确的地址应该是：https://github.com/NiuTrans/Classical-Modern.git

**Comment by xiu-ze** [comment]
您好，感谢您的关注，正确地址应该是：https://github.com/NiuTrans/Classical-Modern.git
在编辑文档时我们出现了失误，感谢您的指正
