### ISSUE TITLE
后汉书张衡列传最后一句有问题

### ISSUE THREAD

**Issue by Skylength** [NiuTrans/Classical-Modern#14]
感谢工作

**Comment by xiu-ze** [comment]
感谢您的反馈和细心检查！针对您提到的问题，我们排查出是HTML标签没有完全去除的问题，我们已经修正这个错误，并更新了数据。再次感谢您的帮助，确保数据的质量是我们共同的目标。如果您还有其他建议或发现更多问题，请随时告知！
