### ISSUE TITLE
能否提供网盘链接或wget地址

### ISSUE THREAD

**Issue by lidh15** [NiuTrans/Classical-Modern#4]
git clone似乎不能支持断点续传，将所有文件直接放在git里在网络条件差的院所几乎无法成功下载，数日以来屡屡失败，观NLP领域凡开源数据集者多有分片打包tar.gz，望能提供更好的下载办法，不胜感激！

**Comment by huchinlp** [comment]
你好，可以尝试在github仓库名的`https`前面加上`https://mirror.ghproxy.com/`
例如`git clone https://mirror.ghproxy.com/https://github.com/NiuTrans/Classical-Modern.git`
同样的，使用`wget`下载`raw.githubusercontent.com`的某个文件也可以直接加上这个前缀，我们在教育网测试速度有10MB/s
