### ISSUE TITLE
几类明显的问题

### ISSUE THREAD

**Issue by wizardk** [NiuTrans/Classical-Modern#5]
感谢开源数据，但是仅仅对比了下北齐书的最后部分，就发现了不少问题，举几个例子。

北齐书的10918行：封述，字君义，渤海蓨人也。
北齐书翻译的10918行：挝述，字昼盖，鲤蓝县人。
人的名、字、籍贯为啥文言文转白话文后都变了？（即便考虑地名变迁，也应是河北景县）

北齐书的10923行：刘昼，字孔昭，渤海阜城人也。
北齐书翻译的10923行：刘昼，字孑昭，渤海阜城人。
孔变成了孑，这是OCR错误造成的？

北齐书的10932行：帝甚纳之，以告丞相高阿那肱等。阿那肱不愿入陈，乃云吴士难信，不须募之。
北齐书翻译的10932行：阿那肱不愿意到陈去，就说呈地人难以信赖，不应该招募。
文言文的前半部分不见了。

北齐书的10946行：士开幼而聪慧，选为国子学生，解悟捷疾，为同业所尚。
北齐书翻译的10918行：士开年少时很聪明，被选为国子学生。
文言文的后半部分不见了。

请问这些白话文数据的原始爬取的地址是什么？以上问题是原始地址就有的问题吗？

**Comment by Luoyingfeng8** [comment]
你好，感谢指出问题，前两个是爬取的原始数据中存在的问题，后两个是分句不当造成的，后续我们会再检查更新下
