### ISSUE TITLE
缺少篇章顺序信息？

### ISSUE THREAD

**Issue by longyuewangdcu** [NiuTrans/Classical-Modern#6]
首先非常感谢分享优秀资源，我在使用过程中发现一个问题就是：

句子是上下文无关的，并没有保留篇章顺序。请问是否有原文顺序？

**Comment by Luoyingfeng8** [comment]
你好，感谢对我们工作的关注，原始爬取的数据是篇章级对齐的，经过后续句子切分、整理后没有保留下原文顺序，后续版本我们会把篇章边界、题目等信息加上~

**Comment by longyuewangdcu** [comment]
期待新版本，感谢回复！
