### ISSUE TITLE
数据版权是否齐全呢？

### ISSUE THREAD

**Issue by zchen0420** [NiuTrans/Classical-Modern#7]
古文和现代文的出处与翻译，是否都有保证质量呢？翻译是谁的？希望作者回答一下，不然很难在公开场合使用。

**Comment by Luoyingfeng8** [comment]
你好，欢迎关注我们的工作，数据是从互联网上收集的，数据质量由数据的来源决定，但我们没有进行整体的评估，我们也计划重新整理数据，包括提供更多细致的信息，欢迎继续关注

**Comment by lidh15** [comment]
说的对，谁来为这个模型的权威性背书，翻译不准确的第一责任人是谁，这是小牛翻译必须正视的严肃问题
