### ISSUE TITLE
能否发布短篇章与《资治通鉴》这部分按篇目分开的语料？

### ISSUE THREAD

**Issue by DongdongY1** [NiuTrans/Classical-Modern#8]
如题。最近的工作需要收集并分类统计现有文言文平行语料的字节数。由于短篇章部分史书与诸子等类混杂在一起，给分类带来了困难。希望能得到按篇目分开的语料库，谢谢 >-<

**Comment by xiu-ze** [comment]
感谢您的关注！目前更新了v2版本的语料，在这个版本的语料中没有合并古籍，可以满足您的需求
